"""initial_schema

Revision ID: ff3afec586b4
Revises: 
Create Date: 2026-03-22 10:37:35.080503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3afec586b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('diametro', sa.Float(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('normas_regras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=200), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('regra_tecnica', sa.Text(), nullable=True),
    sa.Column('aplicavel_a', sa.Text(), nullable=True),
    sa.Column('fonte_referencia', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('altura_m', sa.Float(), nullable=True),
    sa.Column('carga_admissivel_dan', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projetos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orgao', sa.String(length=100), nullable=True),
    sa.Column('ns', sa.String(length=50), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('estudado_por', sa.String(length=100), nullable=True),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('data_estudo', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_table('pontos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('projeto_id', sa.UUID(), nullable=False),
    sa.Column('ponto', sa.String(length=50), nullable=False),
    sa.Column('tipo_poste', sa.String(length=50), nullable=True),
    sa.Column('modelo_poste', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'ponto', name='_projeto_ponto_uc')
    )
    op.create_table('niveis_calculo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ponto_id', sa.UUID(), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('altura_poste', sa.Float(), nullable=True),
    sa.Column('altura_ancoragem', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ponto_id'], ['pontos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ponto_id', 'nivel', name='_ponto_nivel_uc')
    )
    op.create_table('resultados_calculo',
    sa.Column('ponto_id', sa.UUID(), nullable=False),
    sa.Column('mt1_tracao', sa.Float(), nullable=True),
    sa.Column('mt1_angulo', sa.Float(), nullable=True),
    sa.Column('mt2_tracao', sa.Float(), nullable=True),
    sa.Column('mt2_angulo', sa.Float(), nullable=True),
    sa.Column('bt_tracao', sa.Float(), nullable=True),
    sa.Column('bt_angulo', sa.Float(), nullable=True),
    sa.Column('btz_tracao', sa.Float(), nullable=True),
    sa.Column('btz_angulo', sa.Float(), nullable=True),
    sa.Column('ral_tracao', sa.Float(), nullable=True),
    sa.Column('ral_angulo', sa.Float(), nullable=True),
    sa.Column('total_tracao', sa.Float(), nullable=True),
    sa.Column('total_angulo', sa.Float(), nullable=True),
    sa.Column('poste_ecc', sa.Float(), nullable=True),
    sa.Column('texto_mt1', sa.Text(), nullable=True),
    sa.Column('texto_mt2', sa.Text(), nullable=True),
    sa.Column('texto_bt', sa.Text(), nullable=True),
    sa.Column('texto_btz', sa.Text(), nullable=True),
    sa.Column('texto_ral', sa.Text(), nullable=True),
    sa.Column('texto_total', sa.Text(), nullable=True),
    sa.Column('calculado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ponto_id'], ['pontos.id'], ),
    sa.PrimaryKeyConstraint('ponto_id')
    )
    op.create_table('travessias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nivel_id', sa.UUID(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('tipo_rede', sa.String(length=50), nullable=True),
    sa.Column('tipo_cabo', sa.String(length=50), nullable=True),
    sa.Column('vao', sa.Float(), nullable=True),
    sa.Column('flecha', sa.Float(), nullable=True),
    sa.Column('angulo', sa.Float(), nullable=True),
    sa.Column('qtd_ligacoes', sa.Float(), nullable=True),
    sa.Column('qtd_cabos', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['nivel_id'], ['niveis_calculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nivel_id', 'posicao', name='_nivel_posicao_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travessias')
    op.drop_table('resultados_calculo')
    op.drop_table('niveis_calculo')
    op.drop_table('pontos')
    op.drop_table('redes')
    op.drop_table('projetos')
    op.drop_table('postes')
    op.drop_table('normas_regras')
    op.drop_table('cabos')
    # ### end Alembic commands ###
